### ISSUE TITLE
Plotting `DiscreteField <: AbstractQuantity` instances with Makie

### ISSUE THREAD

**Issue by Cmurilochem** [GalerkinToolkit/GalerkinToolkit.jl#119]
@fverdugo, while working on the first notebook I noticed that we currently do not implement a Makie plot type for `AbstractQuantity`s.

While in `WriteVTK` I would do something like:

```julia
WriteVTK.vtk_grid("Ω",Ω) do plt
    GT.plot!(plt,uhd;label="uhd")
end
```

to plot the uhd `DiscreteField`, the Makie version is more laborious:

```julia
plt = GT.plot(Ω)
GT.plot!(plt,g;label="uhd")
GLMakie.plot(plt,color=GT.NodeData("uhd"))
```

Would it make sense to implement a 
```julia
function Makie.plot!(sc::MakiePlot{<:Tuple{<:GalerkinToolkit.AbstractQuantity}})
```
?

**Comment by fverdugo** [comment]
Hi @Cmurilochem 

To plot a field I do this one:
```julia
GLMakie.plot(Ω,color=uhd)
```

Is this enough for you?


What I don't like about 

```julia
GLMakie.plot(uhd)
```

is that the argument `color` does not makes sense anymore.

**Comment by Cmurilochem** [comment]
Thanks @fverdugo. It works perfectly in the notebook https://github.com/GalerkinToolkit/GalerkinToolkit.jl/blob/add_tutorials_to_docs/notebooks/t001_poisson.ipynb
