### ISSUE TITLE
Use Makie instead of paraview as the default visualization method in the tutorials

### ISSUE THREAD

**Issue by fverdugo** [GalerkinToolkit/GalerkinToolkit.jl#90]
WIP in this branch: https://github.com/fverdugo/GalerkinToolkit.jl/tree/makie

cc @raar1 @Cmurilochem 

I have some low level functions already:

![Screenshot from 2024-09-24 18-00-52](https://github.com/user-attachments/assets/842ff2cc-93e3-4f5f-983d-a405d637d299)

**Comment by fverdugo** [comment]
Basic tooling added in https://github.com/fverdugo/GalerkinToolkit.jl/commit/05d36d2ee18d4b60e954266de2195499184ad370 to visualize with Makie. It Should be enough for the Poisson tutorial. 

Some important details missing:

### Fix before merging

- [ ] Use an Extension module instead of adding Makie directly as a dependency: https://www.youtube.com/watch?v=TiIZlQhFzyk
- [ ] vtk_plot vs save_vtk (redundant). Maybe keep the first, but using the low level functions of the second.

### Fix later

- [ ] Fix shadows (orientation of triangles)
- [ ] Add suport for quads/hexs (simplexify)
- [ ] Fix camera positioning
- [ ] Fix ugly edges
- [ ] Visualization of PMeshes

We can merge a first version to main after fixing the first and second items. In this way we can already write the tutorials using these new functions. The other items can be fixed later.

**Comment by fverdugo** [comment]
@Cmurilochem the branch below is ready to start with the extension module

https://github.com/fverdugo/GalerkinToolkit.jl/tree/makie

**Comment by Cmurilochem** [comment]
> @Cmurilochem the branch below is ready to start with the extension module
> 
> https://github.com/fverdugo/GalerkinToolkit.jl/tree/makie

Thanks @fverdugo. I will start today looking into it.
