### ISSUE TITLE
Check if there is anything in the BestieTemplate that would make sense to use here

### ISSUE THREAD

**Issue by raar1** [GalerkinToolkit/GalerkinToolkit.jl#97]
I haven't looked too deeply into this, but at NLeSC people have recently made a release of their Julia repo template which implements various best practices for packaging:
<https://abelsiqueira.com/BestieTemplate.jl/stable/10-full-guide/>

It's possible this repo already ticks all the boxes (if so, great!) but we could look into it.

**Comment by Cmurilochem** [comment]
@fverdugo I agree with @raar1. To start with, I think we should look into features like [JuliaFormatter](https://domluna.github.io/JuliaFormatter.jl/stable/) and/or pre-commit hooks, e.g., [here](https://github.com/abelsiqueira/BestieTemplate.jl/blob/main/.pre-commit-config.yaml).

**Comment by raar1** [comment]
Apparently this can work with existing packages. Let's investigate this.

**Comment by raar1** [comment]
We have investigated the changes in PR #107 and selected the features we want, now in issue #121
